export type IconName =
  | 'logo'
  | 'search'
  | 'heart'
  | 'heart-filled'
  | 'sun'
  | 'moon'
  | 'chevron-left'
  | 'chevron-right'
  | 'image-placeholder'
  | 'chevron-down'
  | 'cross'
  | 'sort'
